set-option -g mouse on
set -g default-terminal "tmux-256color"

# reload config file
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display "Sourced tmux.conf"

# Ctrl + Option vim keys to switch windows
bind -n C-s choose-session

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Catpuccin theme
set -g @plugin 'catppuccin/tmux#v2.1.3'
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_flags "icon"
set -g @catppuccin_window_text " #W #{b:pane_current_path}"
set -g @catppuccin_window_current_text " #W #{pane_current_path}"

# Load catppuccin
run ~/.config/tmux/plugins/tmux/catppuccin.tmux

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 200
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"

# Or, if using TPM, just run TPM
set -g base-index 1              # start indexing windows at 1 instead of 0
set -g renumber-windows on       # renumber all windows when any window is closed
set -g set-clipboard on          # use system clipboard
set -g status-position top       # macOS / darwin style


# Open panes in current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind 'w' new-window -c "#{pane_current_path}"

# Automatic installation of TPM and all plugins, that are registered via TPM
if "test ! -d ~/.config/tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm && ~/.config/tmux/plugins/tpm/bin/install_plugins'"
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
